version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"  # Adjusted path to init.sql    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - "5432:5432"
    
    

  
  
