services:
  - type: web
    name: backend
    env: docker
    plan: free
    repo: https://github.com/AbhishekBhamare/Expense
    dockerfilePath: ./backend/Dockerfile
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: NODE_ENV
        value: production
      - key: PGHOST
        value: db
      - key: PGUSER
        value: Abhishek
      - key: PGPASSWORD
        value: pass123
      - key: PGDATABASE
        value: pf_database
      - key: PGPORT
        value: 5432
  - type: database
    name: db
    plan: free
    image: postgres:latest
    envVars:
      - key: POSTGRES_USER
        value: Abhishek
      - key: POSTGRES_PASSWORD
        value: pass123
      - key: POSTGRES_DB
        value: pf_database
